### ISSUE TITLE
Allow dev mode features to be defused after build

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#292]
I'm interested to see if we can improve dx/user confidence by disabling dev mode features after a build.

For example a user thought that there was a bug because require.resolve used on a ts file for makeSchema({ contextType }) config would lead to a path to a JS file after build. In turn this would lead to an error in typegen which asserts the file path must be to a .ts extenson file. Actually what happened was the user was running e.g. node dist/index with not NODE_ENV=production. These integration effects are unpredictable to most users and even if they don't always represent a valid combination of states users generally cannot be expected to know every permutation of this. It should just be impossible for them to get into these states in the first place.

[https://github.com/prisma/prisma-examples/pull/867#issuecomment-545400592](https://github.com/prisma/prisma-examples/pull/867#issuecomment-545400592)

**Comment by tgriesser** [comment]
Before we solve these workflow inconveniences with new code and changes, I really think we should take more of an effort to improve the core documentation, specifically around type generation. 

I think that giving users, as well as ourselves an opportunity to understand what's going on will go a long way to the success of the library, and may also clarify / illuminate better solutions to the underlying problems.

For example, the change made in https://github.com/prisma/prisma-examples/pull/867 was likely incorrect, and @iRoachie is correct in pointing out that the context is indeed intended to be pointing to the `.ts` file, but the rationale for this is not documented/explained anywhere. 

The solution [he suggested](https://github.com/prisma/prisma-examples/issues/866#issue-509750502):

```diff
- source: require.resolve('./context.ts'),
+ source: require.resolve('../src/context.ts'),
```

is likely what I would have suggested as well, that the path to the context should work independent of the directory it's in. 

In fact, this is the approach I take in my use w/ Cypress - hardcoding the module paths to the context & sources for this exact reason:

```ts
sources: [
  {
    source: '@packages/types/src/db.ts',
    alias: 'dbt',
    typeMatch: (name) =>
      new RegExp(`(?:interface|type|class)\\s+(${name}s?)\\W`, 'g'),
  },
  {
    source: '@packages/data-context/src/DataContext.ts',
    alias: 't',
  },
],
```

> Actually what happened was the user was running e.g. node dist/index with not NODE_ENV=production. 

This wasn't the issue, because the `require.resolve` is executed top-level in a module, and errors if it doesn't resolve the file. So essentially, by removing the `.ts`, I believe it fixed the fact that it was "broken" in production, but it now doesn't work in development either.

Anyway, what I'm getting it is that there are pages and pages of documentation missing explaining the rationale behind how/why things are the way they are, and in order to make sustainable changes we may first want to start with that, and then add changes.

**Comment by jasonkuhrt** [comment]
> This wasn't the issue, because the require.resolve is executed top-level in a module, and errors if it doesn't resolve the file. 

I am aware of those two points. But not sure what your point is here.

> So essentially, by removing the .ts, I believe it fixed the fact that it was "broken" in production, but it now doesn't work in development either.

It does work in development:

![image](https://user-images.githubusercontent.com/284476/67859606-709edd80-faf2-11e9-8a86-abdca474c68d.png)

But anyways we are aligned on your point. We have multiple new docs issues, aside from the backlog already present. A new one that broadly aims to tackle core workflow aspects is https://github.com/prisma-labs/nexus/issues/285.

**Comment by jasonkuhrt** [comment]
After talking with @Weakky we determined a better way to achieve this without any change to `nexus` is to codegen `process.env.NEXUS_CONFIG` settings around the app's entry point. Tracking that here https://github.com/prisma-labs/nexus-cli/issues/7.
