### ISSUE TITLE
Plugin: Query Cost Analysis

### ISSUE THREAD

**Issue by jhalborg** [prisma-labs/nexus#307]
Hey 👋

I'm researching how to best do Demand Control for GraphQL, and found a great article from Spectrum [here](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b). Under the title "Implementing Query Cost Analysis", they mention three libraries one can use to manage query costs:

1. [graphql-validation-complexity](https://github.com/4Catalyzer/graphql-validation-complexity)
2. [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis)
3. [graphql-query-complexity](https://github.com/slicknode/graphql-query-complexity)

Of those, it seems only (2) can be used with Nexus, at it provides the option to pass a `costMap` as an `options` object to the Apollo/Express server. This is usable, but I'd much prefer the option to be able to assign a cost for fields/queries along with the type/query declaration itself, that'd make it much easier to work with. 

The other two rely on either custom directives in the SDL, or custom extensions to the `GraphQLObjectType` as far as I can tell. 

Perhaps it'd be a good idea to add a custom `complexity` or `cost` field to Nexus types/fields, that would allow a cost calculation for queries? Something a la the way [TypeGraphQL](https://typegraphql.ml/docs/complexity.html) does it, perhaps? Or is there another/better way?

Thanks :-)

**Comment by tgriesser** [comment]
Hey! As soon as #242 is merged & `0.12.0` is released, I will begin opening tickets that are "Request for Plugin". This is definitely one I had in mind, was thinking something similar to [complexity & depth](https://graphql-ruby.org/queries/complexity_and_depth.html) in graphql-ruby. 

Because of the way the new plugin system works, it is possible for the plugin to include the typings for this metadata to be defined inline on the field level in a type-safe way:

```ts
t.int('expensiveOperation', {
  cost: 20,
  // ...
})
```
Then it could leverage [`graphql-query-complexity`](https://github.com/slicknode/graphql-query-complexity) in the same way TypeGraphQL does!

**Comment by jhalborg** [comment]
That sounds great @tgriesser ! 

Not quite sure if by "opening tieckets that request plugins", you mean that it will be up to community members to implement such features, or if it is still the plan for the `prisma-labs` team to implement such plugins?

Any way to see a roadmap of sorts for the project?
